image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: ignore
  - port: 5432
    onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: nest start
    command: npm run start:dev
  - init: | # runs during pre-build and open a terminal at right
      npm install
      npm run build

vscode:
  extensions:
    - ashinzekene.nestjs@1.4.0:AkD5nGSQKUH/DgLg/+4p4Q==
    - Orta.vscode-jest@3.2.0:adbRMTNfxv/Rzc4SOP/c3g==
    - esbenp.prettier-vscode@4.7.0:kgoYSh1LwTixKtJtQWtodQ==
    - dbaeumer.vscode-eslint@2.1.5:9Wg0Glx/TwD8ElFBg+FKcQ==
    - VisualStudioExptTeam.vscodeintellicode@1.2.7:ME0wHThZYNfylGMeww9UQA==
