name: reviewdog

on:
  pull_request:
    branches: [master]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: "{src,apps,libs,test}/**/*.ts"
          fail_on_error: true
